### ISSUE TITLE
Compatibility with vite - TypeError: Cannot set properties of undefined (setting 'version')

### ISSUE THREAD

**Issue by kayluhb** [algolia/search-insights.js#530]
When attempting to use this package with vite, it is throwing the following error when vite is configured to use this package as commonjs.

```js
TypeError: Cannot set properties of undefined (setting 'version')
    at /Users/user/Projects/hydrogen-storefront/node_modules/search-insights/index-browser.cjs.js:6:25
    at Array.forEach (<anonymous>)
    at /Users/user/Projects/hydrogen-storefront/node_modules/search-insights/index-browser.cjs.js:4:17
    at Object.runViteModule (Users/user/Projects/hydrogen-storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1181:11)
    at ViteRuntime.directRequest (Users/user/Projects/hydrogen-storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:60)
    at ViteRuntime.cachedRequest (Users/user/Projects/hydrogen-storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:950:79)
    at /app/components/Analytics.tsx:3:31
    at Object.runViteModule (Users/user/Projects/hydrogen-storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1181:11)
    at ViteRuntime.directRequest (Users/user/Projects/hydrogen-storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:1026:60)
    at ViteRuntime.cachedRequest (Users/user/Projects/hydrogen-storefront/node_modules/@shopify/mini-oxygen/dist/vite/worker-entry.js:950:79)
```

**Comment by JasonBerry** [comment]
Related to #356.

Released in [2.16.0](https://github.com/algolia/search-insights.js/releases/tag/v2.16.0)
