### ISSUE TITLE
Failed to resolve entry for package "search-insights"

### ISSUE THREAD

**Issue by malulm** [algolia/search-insights.js#543]
I'm encountering an error during the build process of a Nuxt.js application when using the search-insights@2.16.0 package. The error message is as follows:

`[error] Nuxt Build Error: [commonjs--resolver] Failed to resolve entry for package "search-insights". The package may have incorrect main/module/exports specified in its package.json.
at packageEntryFailure (node_modules/.pnpm/vite@5.3.5_@types+node@18.19.43_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:46351:15)
at resolvePackageEntry (node_modules/.pnpm/vite@5.3.5_@types+node@18.19.43_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:46348:3)
at tryNodeResolve (node_modules/.pnpm/vite@5.3.5_@types+node@18.19.43_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:46164:16)
at Object.resolveId (node_modules/.pnpm/vite@5.3.5_@types+node@18.19.43_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:45914:19)
at node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19892:40
at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19792:28)
at async resolveId (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:18466:26)
at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:18869:15)
at async Object.resolveId (node_modules/.pnpm/vite@5.3.5_@types+node@18.19.43_sass@1.69.5/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:12802:10)
at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19792:28)
`

This issue prevents the CommonJS resolver from locating the correct entry point for the package. The error occurs during the bundling phase, making it impossible to successfully build the application.

The error does not occur while using search-insights@2.15.0

Thank you!

**Comment by josemukorivo** [comment]
experienced a similar error today, had to rollback.

**Comment by JClackett** [comment]
yeah 2.16.0 breaks typescript types
